---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.13.0
    hooks:
      - id: yamlfix
        exclude: ^.github/

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.20.3
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: >-
          env ANSIBLE_COLLECTIONS_PATHS=vendor/collections
          env ANSIBLE_ROLES_PATH=vendor/roles
          ansible-lint --config-file .ansible-lint
        pass_filenames: false
        files: \.(yaml|yml)$
        args:
          - --profile=production
