---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  post_tasks:
    - name: Install docker python module
      ansible.builtin.pip:
        name: docker
        state: present
        extra_args: "{{ '--break-system-packages' if ansible_distribution_release == 'bookworm' else '' }}"

    - name: Add /etc/docker directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: 0755

    - name: Add docker daemon.json
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        mode: 0644
        content: |-
          {
            "log-opts": {
              "max-size": "100m"
            },
            "log-driver": "json-file"
          }
