---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    hello_world_output: "\nHello from Docker!\nThis message shows that your installation appears to be working correctly.\n\nTo generate this\
      \ message, Docker took the following steps:\n 1. The Docker client contacted the Docker daemon.\n 2. The Docker daemon pulled the \"hello-world\"\
      \ image from the Docker Hub.\n    (amd64)\n 3. The Docker daemon created a new container from that image which runs the\n    executable\
      \ that produces the output you are currently reading.\n 4. The Docker daemon streamed that output to the Docker client, which sent it\n\
      \    to your terminal.\n\nTo try something more ambitious, you can run an Ubuntu container with:\n $ docker run -it ubuntu bash\n\nShare\
      \ images, automate workflows, and more with a free Docker ID:\n https://hub.docker.com/\n\nFor more examples and ideas, visit:\n https://docs.docker.com/get-started/\n\
      \n"

  tasks:
    - name: Run hello-world
      register: hello_world
      failed_when: hello_world.container.Output != hello_world_output
      changed_when: hello_world.container.Output != hello_world_output
      community.docker.docker_container:
        image: hello-world
        name: hello-world
        detach: false
        cleanup: true
