---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
    role-file: molecule/requirements.yml

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  playbooks:
    prepare: ${PREPARE_PLAYBOOK:-../common/prepare.yml}
    converge: ${CONVERGE_PLAYBOOK:-../common/converge.yml}
    verify: ${VERIFY_PLAYBOOK:-../common/verify.yml}

  inventory:
    group_vars:
      all:
        docker_version: ${TEST_DOCKER_VERSION:-latest}

verifier:
  name: ansible
