---
- name: Ensure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Ensure /etc/docker/daemon.json has chosen options
  ansible.builtin.copy:
    content: '{{ docker_daemon_options | to_nice_json }}'
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: Restart Docker
