---
- name: Ensure 'docker' group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user(s) to 'docker' group
  ansible.builtin.user:
    name: '{{ item }}'
    groups: docker
    append: true
  loop: '{{ docker_users }}'
